# link from ~/.config/helix/languages.toml

[[language]]
name = "c"
language-servers = [ { name = "clangd", args = ["--header-insertion=never"] } ]

[[language]]
name = "cpp"
language-servers = [ { name = "clangd", args = ["--header-insertion=never"] } ]
